name: Python Unit Tests

on: [push, pull_request] # Roda sempre que houver push ou abrir um PR

jobs:
  build:
    runs-on: ubuntu-latest # Usa um servidor Linux do GitHub

    steps:
    - uses: actions/checkout@v3 # Baixa o código no servidor

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # Define a versão do Python


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Run Tests
      # Para o Actions achar a pasta 'tests' dentro da estrutura
      working-directory: ./Empresas/Concessionaria
      run: |
        # Comando para descobrir e rodar os testes na pasta tests
        python -m unittest discover tests
